### ISSUE TITLE
Error: Invalid URI "/query"

### ISSUE THREAD

**Issue by jfultz22** [tannerjt/AGStoShapefile#5]
I am getting the error in image below using the attached services file. Any ideas as to the cause?

![image](https://cloud.githubusercontent.com/assets/13054782/12153880/0931b2d6-b482-11e5-8268-2ea5d2108bcd.png)

[services.txt](https://github.com/tannerjt/AGStoShapefile/files/80331/services.txt)

**Comment by jfultz22** [comment]
just saw that this same error was already listed as a closed issue. I installed the package mentioned in the other thread and still get the same error.

**Comment by OterLabb** [comment]
Same error here, tried on two different computers with Windows 10. Both with GDAL core installed and not installed. Tried "npm install" and "npm install ogr2ogr" both with cmd.exe with admin rights and node.js command prompt. Also tried several different urls/arcgis servers, no luck!

![image](https://cloud.githubusercontent.com/assets/7389562/13254251/da7faaf8-da40-11e5-905b-23ab917d92c5.png)

**Comment by tannerjt** [comment]
This should be fixed in the latest release.  Just do a git pull and run the tool again.  This specific error was caused because it was treating a 'new line' as an entry.

**Comment by tannerjt** [comment]
If it works now with the latest update, let me know and I'll close the issue.

**Comment by OterLabb** [comment]
Awsome, i will try it tomorrow ☺

**Comment by OterLabb** [comment]
Hmm, I still get a error message. Posted log on pastebin
http://pastebin.com/AFCJrgWb

**Comment by jfultz22** [comment]
I am still getting the same error message as well.

**Comment by tannerjt** [comment]
From your error, it looks like your GDAL tools are not setup correctly.  Type ogr2ogr in your command line and see if it returns anything.  The same error was happening [here](https://github.com/tannerjt/AGStoShapefile/issues/3) but installing GDAL corrected it.  If you're on windows you can add it to your system environment path variables.

**Comment by tannerjt** [comment]
If you're on mac or linux, you can try this step: [gdal guide on mapbox](https://www.mapbox.com/tilemill/docs/guides/gdal/)

**Comment by tannerjt** [comment]
And here is a [guide for windows](http://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows)

**Comment by jfultz22** [comment]
That got it working. Thanks!

**Comment by OterLabb** [comment]
Works here too, thanks :) 

I had a question not about his topic..
I guess its not possible to download raster data with this tool, but do you know if its possible?

**Comment by tannerjt** [comment]
Not currently raster, it can only extract features from a dynamic map or feature service.  Glad it's working.  I'll close the issue.
